version: '3'
services:
  zookeeper:
    container_name: zookeeper_kafka
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    container_name: kafka_kafka
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "transaction-1:1:3,transaction-2:1:1:compact"
  cassandra:
    container_name: cassandra_kafka
    image: cassandra:4.0
    ports:
      - '9069:9069'
    expose:
      - '9069'
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix